"""
Verify Python bindings produce output identical to the standalone C program.

Compares binding output line-by-line against c_笔.txt, c_线段.txt, c_中枢.txt
which were generated by the C standalone build (verified against Python reference).
"""

import os
import sys
import threading
import unittest
from concurrent.futures import ThreadPoolExecutor, as_completed

# Point to the shared library
os.environ.setdefault('CHAN_C99_LIB',
                       os.path.join(os.path.dirname(__file__), '..', 'libchan.so'))

from chan_c99 import (观察者, 缠论配置, K线, 笔, 线段, 中枢, 动态数组,
                       缠论K线, 分型, 背驰分析, _设置自定义strrepr)
from chan_c99.enums import 相对方向


DATA_FILE = os.path.join(os.path.dirname(__file__), '..',
                          'btcusd-300-1761327300-1776327900.nb')
REF_DIR = os.path.join(os.path.dirname(__file__), '..')


def format_stroke(s: 笔) -> str:
    """Format a stroke exactly like main() in chan.c writes to c_笔.txt."""
    direction = '上' if s.方向 == '向上' else '下'
    return (f'{s.序号} {s.级别} {direction} '
            f'{s.高:.6f} {s.低:.6f} '
            f'{s.文.时间戳} {s.武.时间戳} '
            f'{s.文.分型特征值:.6f} {s.武.分型特征值:.6f}')


def format_segment(seg: 线段) -> str:
    """Format a segment exactly like main() in chan.c writes to c_线段.txt."""
    direction = '上' if seg.方向 == '向上' else '下'
    from chan_c99._bindings import _ensure_lib
    base_indices = ' '.join(str(s.序号) for s in seg.基础序列)
    return (f'{seg.序号} {seg.级别} {direction} '
            f'{seg.高:.6f} {seg.低:.6f} '
            f'{len(seg.基础序列)} '
            f'{seg.文.时间戳} {seg.武.时间戳} '
            f'{seg.文.分型特征值:.6f} {seg.武.分型特征值:.6f} '
            f'{base_indices}')


def format_hub(h: 中枢) -> str:
    """Format a hub exactly like main() in chan.c writes to c_中枢.txt."""
    elements = ' '.join(f'{e.标识}_{e.序号}' for e in h.元素)
    return (f'{h.序号} {h.级别} {h.标识} '
            f'{h.高:.6f} {h.低:.6f} '
            f'{len(h.元素)} {elements}')


class TestConsistency(unittest.TestCase):
    """Verify C bindings match the reference C output."""

    @classmethod
    def setUpClass(cls):
        if not os.path.exists(DATA_FILE):
            raise unittest.SkipTest(f'Data file not found: {DATA_FILE}')
        cls.config = 缠论配置(no_push=True)
        cls.obs = 观察者.读取数据文件(DATA_FILE, cls.config)

    @classmethod
    def tearDownClass(cls):
        if hasattr(cls, 'obs'):
            cls.obs.release()

    def _read_ref(self, filename):
        with open(os.path.join(REF_DIR, filename), 'r') as f:
            return [line.rstrip('\n') for line in f if line.strip()]

    def test_stroke_count(self):
        self.assertEqual(len(self.obs.笔序列), 2796)

    def test_segment_count(self):
        self.assertEqual(len(self.obs.线段序列), 374)

    def test_hub_count(self):
        self.assertEqual(len(self.obs.中枢序列), 48)

    def test_raw_kline_count(self):
        self.assertEqual(len(self.obs.普通K线序列), 50003)

    def test_stroke_output_matches_reference(self):
        """Compare stroke text output against c_笔.txt."""
        ref_lines = self._read_ref('c_笔.txt')
        self.assertEqual(len(ref_lines), 2796,
                          f'Reference has {len(ref_lines)} strokes, expected 2796')

        for i, ref_line in enumerate(ref_lines):
            s = self.obs.笔序列[i]
            out = format_stroke(s)
            self.assertEqual(out, ref_line,
                              f'Stroke[{i}] differs:\n  binding: {out}\n  ref:     {ref_line}')

    def test_segment_output_matches_reference(self):
        """Compare segment text output against c_线段.txt."""
        ref_lines = self._read_ref('c_线段.txt')
        self.assertEqual(len(ref_lines), 374,
                          f'Reference has {len(ref_lines)} segments, expected 374')

        for i, ref_line in enumerate(ref_lines):
            seg = self.obs.线段序列[i]
            out = format_segment(seg)
            # Reference has 四象 at token[3]; binding output omits it.
            # ref:  idx lvl dir 四象 high low len wen.ts wu.ts wen.fv wu.fv indices...
            # out:  idx lvl dir      high low len wen.ts wu.ts wen.fv wu.fv indices...
            out_tokens = out.split()
            ref_tokens = ref_line.split()
            self.assertEqual(out_tokens[:3], ref_tokens[:3],
                              f'Segment[{i}] header differs')
            self.assertEqual(out_tokens[3:10], ref_tokens[4:11],
                              f'Segment[{i}] fields differ')
            self.assertEqual(out_tokens[10:], ref_tokens[11:],
                              f'Segment[{i}] base sequence differs')

    def test_hub_output_matches_reference(self):
        """Compare hub text output against c_中枢.txt."""
        ref_lines = self._read_ref('c_中枢.txt')
        self.assertEqual(len(ref_lines), 48,
                          f'Reference has {len(ref_lines)} hubs, expected 48')

        for i, ref_line in enumerate(ref_lines):
            h = self.obs.中枢序列[i]
            out = format_hub(h)
            self.assertEqual(out, ref_line,
                              f'Hub[{i}] differs:\n  binding: {out}\n  ref:     {ref_line}')

    def test_first_stroke_fields(self):
        """Spot-check the first stroke's key fields."""
        s0 = self.obs.笔序列[0]
        self.assertEqual(s0.序号, 0)
        self.assertEqual(s0.方向, '向上')
        self.assertAlmostEqual(s0.高, 110956.0, places=4)
        self.assertAlmostEqual(s0.低, 110175.0, places=4)
        self.assertEqual(s0.文.时间戳, 1761328800)
        self.assertEqual(s0.武.时间戳, 1761333900)

    def test_first_hub_fields(self):
        """Spot-check the first hub's key fields."""
        h0 = self.obs.中枢序列[0]
        self.assertEqual(h0.序号, 0)
        self.assertTrue(h0.完整性)
        self.assertAlmostEqual(h0.高, 113992.0, places=4)
        self.assertAlmostEqual(h0.低, 112933.0, places=4)
        self.assertEqual(len(h0.元素), 8)

    def test_incremental_equals_batch(self):
        """Verify incremental feed produces same results as batch load."""
        inc_config = 缠论配置(no_push=True)
        inc_obs = 观察者('BTCUSD', 300, inc_config)

        for i in range(len(self.obs.普通K线序列)):
            k = self.obs.普通K线序列[i]
            clone = K线.创建普K(k.标识, k.时间戳,
                               k.开盘价, k.高, k.低, k.收盘价,
                               k.成交量, k.序号, k.周期)
            inc_obs.增加原始K线(clone)
            clone.release()

        # Compare final counts
        self.assertEqual(len(inc_obs.笔序列), len(self.obs.笔序列),
                          'Incremental stroke count differs from batch')
        self.assertEqual(len(inc_obs.线段序列), len(self.obs.线段序列),
                          'Incremental segment count differs from batch')
        self.assertEqual(len(inc_obs.中枢序列), len(self.obs.中枢序列),
                          'Incremental hub count differs from batch')

        # Spot-check first and last stroke
        if len(inc_obs.笔序列) > 0:
            inc_s0 = inc_obs.笔序列[0]
            s0 = self.obs.笔序列[0]
            self.assertEqual(inc_s0.序号, s0.序号)
            self.assertEqual(inc_s0.方向, s0.方向)
            self.assertAlmostEqual(inc_s0.高, s0.高, places=4)
            self.assertAlmostEqual(inc_s0.低, s0.低, places=4)

        inc_obs.release()


class Test动态数组(unittest.TestCase):
    """测试动态数组 — Python 列表风格的 C 动态数组包装。"""

    @classmethod
    def setUpClass(cls):
        if not os.path.exists(DATA_FILE):
            raise unittest.SkipTest(f'Data file not found: {DATA_FILE}')
        cls.config = 缠论配置(no_push=True)
        cls.obs = 观察者.读取数据文件(DATA_FILE, cls.config)

    @classmethod
    def tearDownClass(cls):
        if hasattr(cls, 'obs'):
            cls.obs.release()

    def setUp(self):
        """每个测试前创建新的空动态数组。"""
        self.da = 动态数组()

    def tearDown(self):
        """不需要显式清理，Python GC 会处理。"""

    # ---- 基本操作 ----

    def test_new_empty(self):
        """新建动态数组长度应为 0。"""
        self.assertEqual(len(self.da), 0)

    def test_append_and_len(self):
        """追加元素后长度应正确增长。"""
        for i in range(5):
            k = self.obs.普通K线序列[i]
            self.da.append(k)
        self.assertEqual(len(self.da), 5)

    def test_append_multiple_types(self):
        """动态数组可混合存储不同类型的缠论对象。"""
        self.da.append(self.obs.普通K线序列[0])      # K线
        self.da.append(self.obs.缠论K线序列[0])      # 缠论K线
        self.da.append(self.obs.分型序列[0])          # 分型
        self.da.append(self.obs.笔序列[0])            # 笔
        self.da.append(self.obs.中枢序列[0])          # 中枢
        self.assertEqual(len(self.da), 5)

    def test_append_rejects_non_chan_object(self):
        """追加非缠论对象应抛出 TypeError。"""
        with self.assertRaises(TypeError):
            self.da.append("not a chan object")
        with self.assertRaises(TypeError):
            self.da.append(42)
        with self.assertRaises(TypeError):
            self.da.append(None)

    # ---- 索引访问 ----

    def test_getitem_positive(self):
        """正索引访问返回正确的元素。"""
        k = self.obs.普通K线序列[0]
        self.da.append(k)
        self.assertEqual(len(self.da), 1)
        # getitem 返回指针信息的对象

    def test_getitem_negative(self):
        """负索引应从末尾倒数。"""
        for i in range(3):
            self.da.append(self.obs.普通K线序列[i])
        # 负索引 -1 应该是最后一个
        self.assertEqual(len(self.da), 3)

    def test_getitem_out_of_range(self):
        """越界访问应抛出 IndexError。"""
        self.da.append(self.obs.普通K线序列[0])
        with self.assertRaises(IndexError):
            _ = self.da[5]
        with self.assertRaises(IndexError):
            _ = self.da[-5]

    # ---- pop 操作 ----

    def test_pop_basic(self):
        """pop 应移除并返回最后一个元素。"""
        for i in range(3):
            self.da.append(self.obs.普通K线序列[i])
        self.assertEqual(len(self.da), 3)
        popped = self.da.pop()
        self.assertEqual(len(self.da), 2)
        self.assertIsNotNone(popped)

    def test_pop_empty(self):
        """空数组 pop 应抛出 IndexError。"""
        with self.assertRaises(IndexError):
            self.da.pop()

    def test_pop_typed(self):
        """pop_typed 应按指定类型返回元素。"""
        self.da.append(self.obs.笔序列[0])
        popped = self.da.pop_typed(笔)
        self.assertEqual(len(self.da), 0)
        self.assertIsInstance(popped, 笔)

    def test_pop_typed_wrong_type(self):
        """pop_typed 参数必须是 PyTypeObject。"""
        self.da.append(self.obs.笔序列[0])
        # pop_typed 要求传入类型对象，传入错误类型会在 C 层处理
        popped = self.da.pop_typed(笔)
        self.assertIsNotNone(popped)

    # ---- clear 操作 ----

    def test_clear(self):
        """clear 应清空数组。"""
        for i in range(10):
            self.da.append(self.obs.普通K线序列[i])
        self.assertEqual(len(self.da), 10)
        self.da.clear()
        self.assertEqual(len(self.da), 0)

    def test_append_after_clear(self):
        """清空后应可继续追加。"""
        self.da.append(self.obs.普通K线序列[0])
        self.da.clear()
        self.da.append(self.obs.普通K线序列[1])
        self.assertEqual(len(self.da), 1)

    # ---- 集成：配合笔类方法 ----

    def test_stroke_次高(self):
        """笔.次高(缠K序列, 相同终点) 应从动态数组正确计算。"""
        for ck in self.obs.缠论K线序列:
            self.da.append(ck)
        result = 笔.次高(self.da, True)
        self.assertIsNotNone(result)
        self.assertIsInstance(result, 缠论K线)

    def test_stroke_次低(self):
        """笔.次低(缠K序列, 相同终点) 应从动态数组正确计算。"""
        for ck in self.obs.缠论K线序列:
            self.da.append(ck)
        result = 笔.次低(self.da, True)
        self.assertIsNotNone(result)
        self.assertIsInstance(result, 缠论K线)

    def test_stroke_实际高点(self):
        """笔.实际高点(缠K序列, 相同终点) 应从动态数组正确计算。"""
        for ck in self.obs.缠论K线序列:
            self.da.append(ck)
        result = 笔.实际高点(self.da, True)
        self.assertIsNotNone(result)
        self.assertIsInstance(result, 缠论K线)

    def test_stroke_实际低点(self):
        """笔.实际低点(缠K序列, 相同终点) 应从动态数组正确计算。"""
        for ck in self.obs.缠论K线序列:
            self.da.append(ck)
        result = 笔.实际低点(self.da, True)
        self.assertIsNotNone(result)
        self.assertIsInstance(result, 缠论K线)

    def test_stroke_获取缠K数量(self):
        """笔.获取缠K数量(缠K序列, 笔序列, 配置) 应从动态数组正确计算。"""
        ck_arr = 动态数组()
        for ck in self.obs.缠论K线序列:
            ck_arr.append(ck)
        s_arr = 动态数组()
        for s in self.obs.笔序列:
            s_arr.append(s)
        count = 笔.获取缠K数量(ck_arr, s_arr, self.config)
        self.assertGreater(count, 0)
        self.assertIsInstance(count, int)

    def test_stroke_以文会友(self):
        """笔.以文会友(笔序列, 文分型) 应从动态数组查找笔。"""
        s0 = self.obs.笔序列[0]
        s_arr = 动态数组()
        for s in self.obs.笔序列:
            s_arr.append(s)
        result = 笔.以文会友(s_arr, s0.文)
        self.assertIsNotNone(result)
        self.assertIsInstance(result, 笔)

    def test_stroke_以武会友(self):
        """笔.以武会友(笔序列, 武分型) 应从动态数组查找笔。"""
        s0 = self.obs.笔序列[0]
        s_arr = 动态数组()
        for s in self.obs.笔序列:
            s_arr.append(s)
        result = 笔.以武会友(s_arr, s0.武)
        self.assertIsNotNone(result)
        self.assertIsInstance(result, 笔)

    def test_stroke_根据缠K找笔(self):
        """笔.根据缠K找笔(笔序列, 缠K, 偏移) 应从动态数组查找笔。"""
        s0 = self.obs.笔序列[0]
        s_arr = 动态数组()
        for s in self.obs.笔序列:
            s_arr.append(s)
        ck_seq = s0.获取缠K序列(self.obs)
        self.assertIsNotNone(ck_seq)
        ck = ck_seq[0]  # 第一个缠K在笔范围内
        result = 笔.根据缠K找笔(s_arr, ck)
        self.assertIsNotNone(result)
        self.assertIsInstance(result, 笔)

    # ---- 集成：配合背驰分析 ----

    def test_divergence_with_dynarray(self):
        """背驰分析方法应能使用动态数组传入普K序列。"""
        s1, s2 = self.obs.笔序列[0], self.obs.笔序列[1]
        k_arr = 动态数组()
        for k in self.obs.普通K线序列:
            k_arr.append(k)
        # 斜率背驰不需要普K序列
        result = 背驰分析.斜率背驰(s1, s2)
        self.assertIsInstance(result, bool)
        # MACD背驰需要普K序列
        result = 背驰分析.MACD背驰(s1, s2, k_arr, 'default')
        self.assertIsInstance(result, bool)

    # ---- 大批量操作 ----

    def test_bulk_append(self):
        """大批量追加 5000 个元素。"""
        for i in range(min(5000, len(self.obs.普通K线序列))):
            self.da.append(self.obs.普通K线序列[i])
        self.assertEqual(len(self.da), min(5000, len(self.obs.普通K线序列)))

    def test_bulk_append_and_clear_repeatedly(self):
        """反复大批量追加→清空应保持稳定。"""
        for _ in range(3):
            for i in range(100):
                self.da.append(self.obs.普通K线序列[i])
            self.assertEqual(len(self.da), 100)
            self.da.clear()
            self.assertEqual(len(self.da), 0)


class Test自定义strrepr(unittest.TestCase):
    """测试 _设置自定义strrepr 自定义 __repr__ / __str__ 回调机制。"""

    @classmethod
    def setUpClass(cls):
        if not os.path.exists(DATA_FILE):
            raise unittest.SkipTest(f'Data file not found: {DATA_FILE}')
        cls.config = 缠论配置(no_push=True)
        cls.obs = 观察者.读取数据文件(DATA_FILE, cls.config)

    @classmethod
    def tearDownClass(cls):
        if hasattr(cls, 'obs'):
            cls.obs.release()

    def setUp(self):
        """每个测试前清除所有类型的自定义回调。"""
        for t in (K线, 缠论K线, 分型, 线段, 笔, 中枢, 动态数组, 缠论配置):
            _设置自定义strrepr(t, '__repr__', None)
            _设置自定义strrepr(t, '__str__', None)

    # ---- 基本功能 ----

    def test_custom_repr_single(self):
        """设置自定义 __repr__ 后 repr() 应返回回调结果。"""
        _设置自定义strrepr(笔, '__repr__', lambda s: f'笔#{s.序号}')
        s = self.obs.笔序列[0]
        self.assertEqual(repr(s), '笔#0')

    def test_custom_str_single(self):
        """设置自定义 __str__ 后 str() 应返回回调结果。"""
        _设置自定义strrepr(笔, '__str__', lambda s: f'[笔 {s.序号}]')
        s = self.obs.笔序列[0]
        self.assertEqual(str(s), '[笔 0]')

    def test_custom_str_falls_back_to_repr(self):
        """未设置 __str__ 时 str() 应回退到 tp_repr（含自定义 __repr__）。"""
        _设置自定义strrepr(笔, '__repr__', lambda s: f'笔#{s.序号}')
        s = self.obs.笔序列[0]
        self.assertEqual(str(s), '笔#0')

    # ---- 移除回调 ----

    def test_remove_custom_repr(self):
        """传入 None 应移除自定义 __repr__，恢复默认输出。"""
        _设置自定义strrepr(笔, '__repr__', lambda s: 'CUSTOM')
        self.assertEqual(repr(self.obs.笔序列[0]), 'CUSTOM')
        _设置自定义strrepr(笔, '__repr__', None)
        # 默认 repr 应包含类型名
        self.assertIn('笔', repr(self.obs.笔序列[0]))
        self.assertNotIn('CUSTOM', repr(self.obs.笔序列[0]))

    def test_remove_custom_str(self):
        """传入 None 应移除自定义 __str__，str() 回退到 repr。"""
        _设置自定义strrepr(笔, '__str__', lambda s: 'CUSTOM_STR')
        self.assertEqual(str(self.obs.笔序列[0]), 'CUSTOM_STR')
        _设置自定义strrepr(笔, '__str__', None)
        self.assertNotEqual(str(self.obs.笔序列[0]), 'CUSTOM_STR')

    # ---- 错误处理 ----

    def test_invalid_name_raises(self):
        """非法名称应抛出 ValueError。"""
        with self.assertRaises(ValueError):
            _设置自定义strrepr(笔, '__add__', lambda s: 'x')

    def test_non_callable_raises(self):
        """非可调用对象应抛出 TypeError。"""
        with self.assertRaises(TypeError):
            _设置自定义strrepr(笔, '__repr__', 'not_callable')

    # ---- 所有类型 ----

    def test_all_types_accept_custom_repr(self):
        """全部 C 类型都应接受自定义 __repr__。"""
        _设置自定义strrepr(K线, '__repr__', lambda x: 'K')
        _设置自定义strrepr(缠论K线, '__repr__', lambda x: 'CK')
        _设置自定义strrepr(分型, '__repr__', lambda x: 'F')
        _设置自定义strrepr(线段, '__repr__', lambda x: 'SEG')
        _设置自定义strrepr(笔, '__repr__', lambda x: 'S')
        _设置自定义strrepr(中枢, '__repr__', lambda x: 'H')
        _设置自定义strrepr(动态数组, '__repr__', lambda x: 'DA')
        _设置自定义strrepr(缠论配置, '__repr__', lambda x: 'CFG')

        k = K线.创建普K('test', 1000, 10.0, 20.0, 5.0, 15.0, 100.0, 0, 300)
        self.assertEqual(repr(k), 'K')
        k.release()

        self.assertEqual(repr(self.obs.缠论K线序列[0]), 'CK')
        self.assertEqual(repr(self.obs.分型序列[0]), 'F')
        self.assertEqual(repr(self.obs.线段序列[0]), 'SEG')
        self.assertEqual(repr(self.obs.笔序列[0]), 'S')
        self.assertEqual(repr(self.obs.中枢序列[0]), 'H')

        da = 动态数组()
        self.assertEqual(repr(da), 'DA')

        self.assertEqual(repr(self.config), 'CFG')

    # ---- 自定义回调中使用复杂属性 ----

    def test_custom_repr_with_fields(self):
        """自定义回调应能访问对象字段构造复杂输出。"""
        _设置自定义strrepr(中枢, '__repr__',
            lambda h: f'Hub#{h.序号} HG={h.高:.2f} LD={h.低:.2f} elem={len(h.元素)}')
        h = self.obs.中枢序列[0]
        r = repr(h)
        self.assertIn('Hub#0', r)
        self.assertIn('HG=', r)
        self.assertIn('LD=', r)
        self.assertIn('elem=8', r)

    def test_custom_str_with_direction(self):
        """自定义 __str__ 应能访问方向字段。"""
        _设置自定义strrepr(笔, '__str__',
            lambda s: f'笔#{s.序号}方向{s.方向}')
        s = self.obs.笔序列[0]
        self.assertEqual(str(s), '笔#0方向向上')


class Test多线程(unittest.TestCase):
    """多线程并发安全测试 —— 验证全局内存池、弱引用计数、动态数组的线程安全性。

    注意：CPython 的 GIL 会串行化 C 扩展调用，本测试验证原子操作的逻辑正确性。
    真正的并发压力测试请用 C 独立程序（chan.c 的 main 函数支持 pthread）。"""

    N_THREADS = 4  # 并发线程数

    @classmethod
    def setUpClass(cls):
        if not os.path.exists(DATA_FILE):
            raise unittest.SkipTest(f'Data file not found: {DATA_FILE}')

    # ---- 并发分析一致性 ----

    def test_parallel_analysis_consistent(self):
        """N 线程同时跑完整分析，结果应完全一致（2796 笔 / 374 线段 / 48 中枢）。"""
        def analyze():
            config = 缠论配置(no_push=True)
            obs = 观察者.读取数据文件(DATA_FILE, config)
            result = (len(obs.笔序列), len(obs.线段序列), len(obs.中枢序列))
            obs.release()
            return result

        with ThreadPoolExecutor(max_workers=self.N_THREADS) as ex:
            futures = [ex.submit(analyze) for _ in range(self.N_THREADS)]
            results = [f.result() for f in as_completed(futures)]

        for i, (strokes, segments, hubs) in enumerate(results):
            self.assertEqual((strokes, segments, hubs), (2796, 374, 48),
                             f'线程 {i}: 笔={strokes} 线段={segments} 中枢={hubs}')

    def test_parallel_incremental_consistent(self):
        """N 线程同时跑增量分析，结果应一致。"""
        config = 缠论配置(no_push=True)
        batch_obs = 观察者.读取数据文件(DATA_FILE, config)
        total = len(batch_obs.普通K线序列)
        expected = (len(batch_obs.笔序列), len(batch_obs.线段序列), len(batch_obs.中枢序列))
        batch_obs.release()

        errors = []
        lock = threading.Lock()

        def run_incremental(thread_id):
            try:
                cfg = 缠论配置(no_push=True)
                obs = 观察者('BTCUSD', 300, cfg)
                # 用固定种子保证每个线程喂入的 K 线一致
                for i in range(total):
                    k = K线.创建普K(
                        f'K{i}', 1761327300 + i * 300,
                        50000.0 + (i % 100), 50100.0 + (i % 100),
                        49900.0 + (i % 100), 50050.0 + (i % 100),
                        100.0, i, 300)
                    obs.增加原始K线(k)
                    k.release()
                result = (len(obs.笔序列), len(obs.线段序列), len(obs.中枢序列))
                obs.release()
                return result
            except Exception as e:
                with lock:
                    errors.append(f'线程 {thread_id}: {e}')
                return None

        with ThreadPoolExecutor(max_workers=self.N_THREADS) as ex:
            futures = {ex.submit(run_incremental, i): i for i in range(self.N_THREADS)}
            for f in as_completed(futures):
                result = f.result()

        self.assertEqual(len(errors), 0, ';\n'.join(errors))

    # ---- 动态数组并发操作 ----

    def test_parallel_dynarray_append(self):
        """N 线程并发向同一动态数组追加元素（压力测试）。"""
        config = 缠论配置(no_push=True)
        obs = 观察者.读取数据文件(DATA_FILE, config)
        da = 动态数组()
        n_per_thread = 500
        errors = []
        lock = threading.Lock()

        def append_batch(start_idx):
            try:
                for i in range(start_idx, start_idx + n_per_thread):
                    da.append(obs.普通K线序列[i % len(obs.普通K线序列)])
            except Exception as e:
                with lock:
                    errors.append(str(e))

        threads = []
        for t in range(self.N_THREADS):
            t_ = threading.Thread(target=append_batch, args=(t * n_per_thread,))
            threads.append(t_)

        for t_ in threads:
            t_.start()
        for t_ in threads:
            t_.join()

        self.assertEqual(len(errors), 0, ';\n'.join(errors))
        self.assertEqual(len(da), self.N_THREADS * n_per_thread)
        obs.release()

    def test_parallel_dynarray_mixed_ops(self):
        """生产者-消费者模式：两个线程追加，两个线程弹出。"""
        config = 缠论配置(no_push=True)
        obs = 观察者.读取数据文件(DATA_FILE, config)
        da = 动态数组()
        total_appends = 200
        appends_done = threading.Barrier(2)  # 等生产者完成后消费者才开始
        errors = []
        lock = threading.Lock()

        def producer(start):
            try:
                for i in range(start, start + total_appends // 2):
                    da.append(obs.笔序列[i % len(obs.笔序列)])
            except Exception as e:
                with lock:
                    errors.append(f'producer: {e}')

        def consumer(n_pops):
            try:
                for _ in range(n_pops):
                    da.pop()
            except Exception as e:
                with lock:
                    errors.append(f'consumer: {e}')

        t1 = threading.Thread(target=producer, args=(0,))
        t2 = threading.Thread(target=producer, args=(total_appends // 2,))
        t3 = threading.Thread(target=consumer, args=(50,))
        t4 = threading.Thread(target=consumer, args=(50,))

        for t in [t1, t2, t3, t4]:
            t.start()
        for t in [t1, t2, t3, t4]:
            t.join()

        self.assertEqual(len(errors), 0, ';\n'.join(errors))
        self.assertEqual(len(da), total_appends - 100)
        obs.release()

    def test_parallel_dynarray_clear_and_append(self):
        """一个线程清空，另一个线程追加，应不崩溃且最终状态一致。"""
        config = 缠论配置(no_push=True)
        obs = 观察者.读取数据文件(DATA_FILE, config)
        da = 动态数组()
        errors = []
        lock = threading.Lock()
        barrier = threading.Barrier(2)

        def appender():
            try:
                barrier.wait()
                for i in range(100):
                    da.append(obs.普通K线序列[i % 100])
            except Exception as e:
                with lock:
                    errors.append(f'appender: {e}')

        def clearer():
            try:
                barrier.wait()
                for _ in range(10):
                    da.clear()
            except Exception as e:
                with lock:
                    errors.append(f'clearer: {e}')

        t1 = threading.Thread(target=appender)
        t2 = threading.Thread(target=clearer)
        t1.start()
        t2.start()
        t1.join()
        t2.join()

        self.assertEqual(len(errors), 0, ';\n'.join(errors))
        obs.release()

    # ---- 池对象跨线程共享 ----

    def test_shared_pool_objects_weak_ref(self):
        """不同线程创建的池内对象之间建立弱引用，弱引用计数应正确。"""
        config = 缠论配置(no_push=True)
        obs = 观察者.读取数据文件(DATA_FILE, config)
        da = 动态数组()

        # 追加一批笔到共享动态数组
        for i in range(min(100, len(obs.笔序列))):
            da.append(obs.笔序列[i])

        errors = []
        lock = threading.Lock()

        def pop_some(n):
            try:
                for _ in range(n):
                    da.pop()
            except Exception as e:
                with lock:
                    errors.append(str(e))

        # 两个线程并发弹出（递减弱引用计数）
        t1 = threading.Thread(target=pop_some, args=(20,))
        t2 = threading.Thread(target=pop_some, args=(20,))
        t1.start()
        t2.start()
        t1.join()
        t2.join()

        self.assertEqual(len(errors), 0, ';\n'.join(errors))
        self.assertEqual(len(da), 60)  # 100 - 20 - 20
        obs.release()
        # 若弱引用计数有误，释放观察者时 assert 或 ASan 会报错

    # ---- 对象生命周期交叉 ----

    def test_concurrent_observer_lifecycle(self):
        """并发创建和释放观察者，全局池复用不应崩溃。"""
        errors = []
        lock = threading.Lock()

        def create_and_release(seed):
            try:
                cfg = 缠论配置(no_push=True)
                obs = 观察者('BTCUSD', 300, cfg)
                for i in range(100):
                    k = K线.创建普K(
                        f'K{seed}_{i}', 1761327300 + i * 300,
                        50000.0 + seed, 50100.0 + seed,
                        49900.0 + seed, 50050.0 + seed,
                        100.0, i, 300)
                    obs.增加原始K线(k)
                    k.release()
                obs.release()
            except Exception as e:
                with lock:
                    errors.append(f'seed={seed}: {e}')

        with ThreadPoolExecutor(max_workers=self.N_THREADS) as ex:
            futures = [ex.submit(create_and_release, i) for i in range(self.N_THREADS)]
            for f in as_completed(futures):
                f.result()

        self.assertEqual(len(errors), 0, ';\n'.join(errors))


if __name__ == '__main__':
    unittest.main(verbosity=2)
